/* eslint-disable @typescript-eslint/no-explicit-any */
import { DataTable } from "@/components/ui/data-table";
import { useMemo, useState } from "react";
import { reportColumns } from "./reportstable/ReportsColumns";
import ReportsTableToolBar from "./reportstable/ReportsTableToolBar";

function ReportsMain() {
  const data = [
    {
      sNo: 1,
      docketNumber: "07042025/eOffice/10",
      zone: "WR",
      division: "HQ",
      designation: "CCE",
      name: "RAKESH GUPTA",
      startDate: "07.04.2025",
      startTime: "12:53",
      endDate: null,
      endTime: null,
      issue: "FMS",
      issueDescription: "Slowness accessing FMS",
      issueResolution:
        "A ticket has been registered with NIC for quick resolution. ticket #20250405194727485066",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "7975610340",
      resolvedByHelpdesk: "ANANDKUMAR",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 1,
      docketNumber: "07042025/eOffice/10",
      zone: "WR",
      division: "HQ",
      designation: "CCE",
      name: "RAKESH GUPTA",
      startDate: "07.04.2025",
      startTime: "12:53",
      endDate: null,
      endTime: null,
      issue: "FMS",
      issueDescription: "Slowness accessing FMS",
      issueResolution:
        "A ticket has been registered with NIC for quick resolution. ticket #20250405194727485066",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "7975610340",
      resolvedByHelpdesk: "ANANDKUMAR",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
    {
      sNo: 2,
      docketNumber: "15052025/eOffice/01",
      zone: "SCR",
      division: "HO",
      designation: "ISSE",
      name: "MUPPIDI HEMANTHA",
      startDate: "15.05.2025",
      startTime: "09:31",
      endDate: "15.05.2025",
      endTime: "09:42",
      issue: "EMD",
      issueDescription: "Employee transfer",
      issueResolution: "Collected transfer details and forwarded to HRMS",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "8857458568",
      resolvedByHelpdesk: "VAJUBABU",
    },
    {
      sNo: 3,
      docketNumber: "16052025/eOffice/02",
      zone: "CR",
      division: "MUMBAI",
      designation: "SSE",
      name: "NISHA SHARMA",
      startDate: "16.05.2025",
      startTime: "10:15",
      endDate: null,
      endTime: null,
      issue: "NETWORK",
      issueDescription: "LAN not working in cabin",
      issueResolution: "Team dispatched to check switch/router configuration",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9876543210",
      resolvedByHelpdesk: "RAHUL",
    },
    {
      sNo: 4,
      docketNumber: "16052025/eOffice/03",
      zone: "NR",
      division: "DELHI",
      designation: "JE",
      name: "SACHIN KUMAR",
      startDate: "16.05.2025",
      startTime: "11:00",
      endDate: "16.05.2025",
      endTime: "11:30",
      issue: "PRINTER",
      issueDescription: "Unable to print from eOffice",
      issueResolution: "Driver updated and test page printed",
      issueType: "MINOR",
      status: "RESOLVED",
      userMobileNumber: "9123456789",
      resolvedByHelpdesk: "DIVYA",
    },
    {
      sNo: 5,
      docketNumber: "16052025/eOffice/04",
      zone: "ER",
      division: "KOLKATA",
      designation: "DSTE",
      name: "PRIYA VERMA",
      startDate: "16.05.2025",
      startTime: "14:22",
      endDate: null,
      endTime: null,
      issue: "INTERNET",
      issueDescription: "Frequent disconnection from VPN",
      issueResolution: "Escalated to ISP; awaiting resolution",
      issueType: "MAJOR",
      status: "PENDING",
      userMobileNumber: "9812345678",
      resolvedByHelpdesk: "MOHAN",
    },
  ];

  const [pagination, setPagination] = useState({
    pageIndex: 0,
    pageSize: 13, // 👈 Set default rows per page here
  });
  const paginatedData = useMemo(() => {
    const start = pagination.pageIndex * pagination.pageSize;
    const end = start + pagination.pageSize;
    return data.slice(start, end);
  }, [data, pagination]);

  return (
    <div className="flex flex-col gap-5">
      <div className="">
        <DataTable
          pagination={pagination}
          setPagination={setPagination}
          data={paginatedData as any}
          columns={reportColumns}
          Toolbar={ReportsTableToolBar}
          totalPages={Math.ceil(data?.length / pagination.pageSize)}
        />
      </div>
    </div>
  );
}

export default ReportsMain;
